version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - pip install
  build:
    commands:
      - echo Build started on 'date'
      - pip run build
artifacts:
  files:
    - '**/*'
  base-directory: build